// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/add": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/add";
  };
  "catchall.tsx": {
    id: "catchall";
    page: "/";
  };
  "./todoadd.tsx": {
    id: "todoadd";
    page: "/add";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "catchall": typeof import("./src/catchall.tsx");
  "todoadd": typeof import("./src/./todoadd.tsx");
};